# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yacht/config/proto/action_noise.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='yacht/config/proto/action_noise.proto',
  package='yacht.config.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n%yacht/config/proto/action_noise.proto\x12\x12yacht.config.proto\"X\n\x11\x41\x63tionNoiseConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04mean\x18\x02 \x01(\x01\x12\r\n\x05sigma\x18\x03 \x01(\x01\x12\r\n\x05theta\x18\x04 \x01(\x01\x12\t\n\x01p\x18\x05 \x01(\x01\x62\x06proto3')
)




_ACTIONNOISECONFIG = _descriptor.Descriptor(
  name='ActionNoiseConfig',
  full_name='yacht.config.proto.ActionNoiseConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='yacht.config.proto.ActionNoiseConfig.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mean', full_name='yacht.config.proto.ActionNoiseConfig.mean', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sigma', full_name='yacht.config.proto.ActionNoiseConfig.sigma', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='theta', full_name='yacht.config.proto.ActionNoiseConfig.theta', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='p', full_name='yacht.config.proto.ActionNoiseConfig.p', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=149,
)

DESCRIPTOR.message_types_by_name['ActionNoiseConfig'] = _ACTIONNOISECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ActionNoiseConfig = _reflection.GeneratedProtocolMessageType('ActionNoiseConfig', (_message.Message,), dict(
  DESCRIPTOR = _ACTIONNOISECONFIG,
  __module__ = 'yacht.config.proto.action_noise_pb2'
  # @@protoc_insertion_point(class_scope:yacht.config.proto.ActionNoiseConfig)
  ))
_sym_db.RegisterMessage(ActionNoiseConfig)


# @@protoc_insertion_point(module_scope)
