# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yacht/config/proto/agent.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from yacht.config.proto import policy_pb2 as yacht_dot_config_dot_proto_dot_policy__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='yacht/config/proto/agent.proto',
  package='yacht.config.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1eyacht/config/proto/agent.proto\x12\x12yacht.config.proto\x1a\x1fyacht/config/proto/policy.proto\"\xa1\x01\n\x0b\x41gentConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x19\n\x11is_classic_method\x18\x02 \x01(\x08\x12\x12\n\nis_teacher\x18\x03 \x01(\x08\x12\x12\n\nis_student\x18\x04 \x01(\x08\x12\x0f\n\x07verbose\x18\x05 \x01(\x08\x12\x30\n\x06policy\x18\x06 \x01(\x0b\x32 .yacht.config.proto.PolicyConfigb\x06proto3')
  ,
  dependencies=[yacht_dot_config_dot_proto_dot_policy__pb2.DESCRIPTOR,])




_AGENTCONFIG = _descriptor.Descriptor(
  name='AgentConfig',
  full_name='yacht.config.proto.AgentConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='yacht.config.proto.AgentConfig.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_classic_method', full_name='yacht.config.proto.AgentConfig.is_classic_method', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_teacher', full_name='yacht.config.proto.AgentConfig.is_teacher', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_student', full_name='yacht.config.proto.AgentConfig.is_student', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='verbose', full_name='yacht.config.proto.AgentConfig.verbose', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='policy', full_name='yacht.config.proto.AgentConfig.policy', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=249,
)

_AGENTCONFIG.fields_by_name['policy'].message_type = yacht_dot_config_dot_proto_dot_policy__pb2._POLICYCONFIG
DESCRIPTOR.message_types_by_name['AgentConfig'] = _AGENTCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AgentConfig = _reflection.GeneratedProtocolMessageType('AgentConfig', (_message.Message,), dict(
  DESCRIPTOR = _AGENTCONFIG,
  __module__ = 'yacht.config.proto.agent_pb2'
  # @@protoc_insertion_point(class_scope:yacht.config.proto.AgentConfig)
  ))
_sym_db.RegisterMessage(AgentConfig)


# @@protoc_insertion_point(module_scope)
