# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yacht/config/proto/agent.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from yacht.config.proto import feature_extractor_pb2 as yacht_dot_config_dot_proto_dot_feature__extractor__pb2
from yacht.config.proto import backbone_pb2 as yacht_dot_config_dot_proto_dot_backbone__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='yacht/config/proto/agent.proto',
  package='yacht.config.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1eyacht/config/proto/agent.proto\x12\x12yacht.config.proto\x1a*yacht/config/proto/feature_extractor.proto\x1a!yacht/config/proto/backbone.proto\"\xa9\x01\n\x0b\x41gentConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07verbose\x18\x02 \x01(\x08\x12\x45\n\x11\x66\x65\x61ture_extractor\x18\x03 \x01(\x0b\x32*.yacht.config.proto.FeatureExtractorConfig\x12\x34\n\x08\x62\x61\x63kbone\x18\x04 \x01(\x0b\x32\".yacht.config.proto.BackboneConfigb\x06proto3')
  ,
  dependencies=[yacht_dot_config_dot_proto_dot_feature__extractor__pb2.DESCRIPTOR,yacht_dot_config_dot_proto_dot_backbone__pb2.DESCRIPTOR,])




_AGENTCONFIG = _descriptor.Descriptor(
  name='AgentConfig',
  full_name='yacht.config.proto.AgentConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='yacht.config.proto.AgentConfig.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='verbose', full_name='yacht.config.proto.AgentConfig.verbose', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feature_extractor', full_name='yacht.config.proto.AgentConfig.feature_extractor', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='backbone', full_name='yacht.config.proto.AgentConfig.backbone', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=303,
)

_AGENTCONFIG.fields_by_name['feature_extractor'].message_type = yacht_dot_config_dot_proto_dot_feature__extractor__pb2._FEATUREEXTRACTORCONFIG
_AGENTCONFIG.fields_by_name['backbone'].message_type = yacht_dot_config_dot_proto_dot_backbone__pb2._BACKBONECONFIG
DESCRIPTOR.message_types_by_name['AgentConfig'] = _AGENTCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AgentConfig = _reflection.GeneratedProtocolMessageType('AgentConfig', (_message.Message,), dict(
  DESCRIPTOR = _AGENTCONFIG,
  __module__ = 'yacht.config.proto.agent_pb2'
  # @@protoc_insertion_point(class_scope:yacht.config.proto.AgentConfig)
  ))
_sym_db.RegisterMessage(AgentConfig)


# @@protoc_insertion_point(module_scope)
