# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yacht/config/proto/backbone.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='yacht/config/proto/backbone.proto',
  package='yacht.config.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n!yacht/config/proto/backbone.proto\x12\x12yacht.config.proto\":\n\x0e\x42\x61\x63kboneConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1a\n\x12input_features_dim\x18\x02 \x01(\x05\x62\x06proto3')
)




_BACKBONECONFIG = _descriptor.Descriptor(
  name='BackboneConfig',
  full_name='yacht.config.proto.BackboneConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='yacht.config.proto.BackboneConfig.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_features_dim', full_name='yacht.config.proto.BackboneConfig.input_features_dim', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=115,
)

DESCRIPTOR.message_types_by_name['BackboneConfig'] = _BACKBONECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BackboneConfig = _reflection.GeneratedProtocolMessageType('BackboneConfig', (_message.Message,), dict(
  DESCRIPTOR = _BACKBONECONFIG,
  __module__ = 'yacht.config.proto.backbone_pb2'
  # @@protoc_insertion_point(class_scope:yacht.config.proto.BackboneConfig)
  ))
_sym_db.RegisterMessage(BackboneConfig)


# @@protoc_insertion_point(module_scope)
