# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yacht/config/proto/backtest.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='yacht/config/proto/backtest.proto',
  package='yacht.config.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n!yacht/config/proto/backtest.proto\x12\x12yacht.config.proto\"U\n\x0e\x42\x61\x63ktestConfig\x12\x0b\n\x03run\x18\x01 \x01(\x08\x12\x15\n\rdeterministic\x18\x02 \x01(\x08\x12\x0f\n\x07tickers\x18\x03 \x03(\t\x12\x0e\n\x06n_runs\x18\x04 \x01(\x05\x62\x06proto3')
)




_BACKTESTCONFIG = _descriptor.Descriptor(
  name='BacktestConfig',
  full_name='yacht.config.proto.BacktestConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='run', full_name='yacht.config.proto.BacktestConfig.run', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deterministic', full_name='yacht.config.proto.BacktestConfig.deterministic', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tickers', full_name='yacht.config.proto.BacktestConfig.tickers', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='n_runs', full_name='yacht.config.proto.BacktestConfig.n_runs', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=142,
)

DESCRIPTOR.message_types_by_name['BacktestConfig'] = _BACKTESTCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BacktestConfig = _reflection.GeneratedProtocolMessageType('BacktestConfig', (_message.Message,), dict(
  DESCRIPTOR = _BACKTESTCONFIG,
  __module__ = 'yacht.config.proto.backtest_pb2'
  # @@protoc_insertion_point(class_scope:yacht.config.proto.BacktestConfig)
  ))
_sym_db.RegisterMessage(BacktestConfig)


# @@protoc_insertion_point(module_scope)
