# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yacht/config/proto/feature_extractor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='yacht/config/proto/feature_extractor.proto',
  package='yacht.config.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n*yacht/config/proto/feature_extractor.proto\x12\x12yacht.config.proto\"<\n\x16\x46\x65\x61tureExtractorConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x14\n\x0c\x66\x65\x61tures_dim\x18\x02 \x01(\x05\x62\x06proto3'
)




_FEATUREEXTRACTORCONFIG = _descriptor.Descriptor(
  name='FeatureExtractorConfig',
  full_name='yacht.config.proto.FeatureExtractorConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='yacht.config.proto.FeatureExtractorConfig.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='features_dim', full_name='yacht.config.proto.FeatureExtractorConfig.features_dim', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=126,
)

DESCRIPTOR.message_types_by_name['FeatureExtractorConfig'] = _FEATUREEXTRACTORCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FeatureExtractorConfig = _reflection.GeneratedProtocolMessageType('FeatureExtractorConfig', (_message.Message,), {
  'DESCRIPTOR' : _FEATUREEXTRACTORCONFIG,
  '__module__' : 'yacht.config.proto.feature_extractor_pb2'
  # @@protoc_insertion_point(class_scope:yacht.config.proto.FeatureExtractorConfig)
  })
_sym_db.RegisterMessage(FeatureExtractorConfig)


# @@protoc_insertion_point(module_scope)
