# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yacht/config/proto/interval.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='yacht/config/proto/interval.proto',
  package='yacht.config.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n!yacht/config/proto/interval.proto\x12\x12yacht.config.proto\",\n\x0eIntervalConfig\x12\r\n\x05start\x18\x01 \x01(\t\x12\x0b\n\x03\x65nd\x18\x02 \x01(\tb\x06proto3')
)




_INTERVALCONFIG = _descriptor.Descriptor(
  name='IntervalConfig',
  full_name='yacht.config.proto.IntervalConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='yacht.config.proto.IntervalConfig.start', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='yacht.config.proto.IntervalConfig.end', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=101,
)

DESCRIPTOR.message_types_by_name['IntervalConfig'] = _INTERVALCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

IntervalConfig = _reflection.GeneratedProtocolMessageType('IntervalConfig', (_message.Message,), dict(
  DESCRIPTOR = _INTERVALCONFIG,
  __module__ = 'yacht.config.proto.interval_pb2'
  # @@protoc_insertion_point(class_scope:yacht.config.proto.IntervalConfig)
  ))
_sym_db.RegisterMessage(IntervalConfig)


# @@protoc_insertion_point(module_scope)
