# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yacht/config/proto/net_architecture.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='yacht/config/proto/net_architecture.proto',
  package='yacht.config.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n)yacht/config/proto/net_architecture.proto\x12\x12yacht.config.proto\"K\n\x15NetArchitectureConfig\x12\x0e\n\x06shared\x18\x01 \x03(\x05\x12\n\n\x02vf\x18\x02 \x03(\x05\x12\n\n\x02qf\x18\x03 \x03(\x05\x12\n\n\x02pi\x18\x04 \x03(\x05\x62\x06proto3')
)




_NETARCHITECTURECONFIG = _descriptor.Descriptor(
  name='NetArchitectureConfig',
  full_name='yacht.config.proto.NetArchitectureConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shared', full_name='yacht.config.proto.NetArchitectureConfig.shared', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vf', full_name='yacht.config.proto.NetArchitectureConfig.vf', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qf', full_name='yacht.config.proto.NetArchitectureConfig.qf', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pi', full_name='yacht.config.proto.NetArchitectureConfig.pi', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=140,
)

DESCRIPTOR.message_types_by_name['NetArchitectureConfig'] = _NETARCHITECTURECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NetArchitectureConfig = _reflection.GeneratedProtocolMessageType('NetArchitectureConfig', (_message.Message,), dict(
  DESCRIPTOR = _NETARCHITECTURECONFIG,
  __module__ = 'yacht.config.proto.net_architecture_pb2'
  # @@protoc_insertion_point(class_scope:yacht.config.proto.NetArchitectureConfig)
  ))
_sym_db.RegisterMessage(NetArchitectureConfig)


# @@protoc_insertion_point(module_scope)
