# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yacht/config/proto/reward_schema.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='yacht/config/proto/reward_schema.proto',
  package='yacht.config.proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n&yacht/config/proto/reward_schema.proto\x12\x12yacht.config.proto\x1a\x19google/protobuf/any.proto\"V\n\x12RewardSchemaConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x16\n\x0ereward_scaling\x18\x02 \x01(\x01\x12\x1a\n\x12\x64\x65nsity_thresholds\x18\x03 \x03(\x01\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_REWARDSCHEMACONFIG = _descriptor.Descriptor(
  name='RewardSchemaConfig',
  full_name='yacht.config.proto.RewardSchemaConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='yacht.config.proto.RewardSchemaConfig.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reward_scaling', full_name='yacht.config.proto.RewardSchemaConfig.reward_scaling', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='density_thresholds', full_name='yacht.config.proto.RewardSchemaConfig.density_thresholds', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=175,
)

DESCRIPTOR.message_types_by_name['RewardSchemaConfig'] = _REWARDSCHEMACONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RewardSchemaConfig = _reflection.GeneratedProtocolMessageType('RewardSchemaConfig', (_message.Message,), {
  'DESCRIPTOR' : _REWARDSCHEMACONFIG,
  '__module__' : 'yacht.config.proto.reward_schema_pb2'
  # @@protoc_insertion_point(class_scope:yacht.config.proto.RewardSchemaConfig)
  })
_sym_db.RegisterMessage(RewardSchemaConfig)


# @@protoc_insertion_point(module_scope)
