project: yacht
entity: yacht
name: SingleAssetOrderExectionNasdaq100
program: tools/tuning/run.py
method: bayes
metric:
  goal: maximize
  name: backtest_on_validation/PA
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--config_file_name"
  - "single_asset_order_execution_nasdaq100_ppo.config.txt"
parameters:
  agent.name:
    distribution: constant
    value: PPO
  agent.policy.activationFn:
    distribution: categorical
    values:
    - Tanh
    - ReLU
  agent.policy.featureExtractor.dropOutP:
    distribution: uniform
    max: 0.8
    min: 0.0
  agent.policy.featureExtractor.name:
    distribution: constant
    value: RecurrentFeatureExtractor
  agent.policy.featureExtractor.featuresDim:
    distribution: categorical
    values:
      - [32, 32, 256]
      - [32, 32, 32, 256]
      - [32, 32, 32, 32, 256]
      - [64, 64, 512]
      - [64, 64, 256]
      - [64, 64, 64, 256]
      - [128, 128, 1024]
  agent.policy.featureExtractor.rnnLayerType:
    distribution: categorical
    values:
      - GRU
      - LSTM
  agent.policy.name:
    distribution: categorical
    values:
    - MlpPolicy
  agent.policy.netArch.shared:
    distribution: categorical
    values:
      - [128]
      - [128, 128]
      - [256]
      - [256, 128]
      - [512]
      - [512, 256]
  agent.policy.netArch.vf:
    distribution: categorical
    values:
      - [16]
      - [32]
      - [64]
  agent.policy.netArch.pi:
    distribution: categorical
    values:
      - [16]
      - [32]
      - [64]
  agent.verbose:
    distribution: constant
    value: "true"
  environment.actionSchema:
    distribution: constant
    value: DiscreteActionScheme
  environment.rewardSchemas:
    distribution: categorical
    values:
      - - name: DecisionMakingRewardSchema
        - name: ActionMagnitudeRewardSchema
          reward_scaling: 0.01
      - - name: DecisionMakingRewardSchema
        - name: ActionMagnitudeRewardSchema
          reward_scaling: 0.005
      - - name: DecisionMakingRewardSchema
        - name: ActionMagnitudeRewardSchema
          reward_scaling: 0.02
  environment.initialCashPosition:
    distribution: normal
    mu: 5000
    sigma: 1000
  environment.nEnvs:
    distribution: int_uniform
    max: 16
    min: 4
  environment.name:
    distribution: constant
    value: OrderExecutionEnvironment-v0
  environment.possibilities:
    distribution: categorical
    values:
      - [0, 0.25, 0.5, 0.75, 1]
      - [0, 0.1, 0.25, 0.5, 0.75, 1]
      - [0, 0.05, 0.1, 0.25, 0.5, 0.75, 1]
  input.backtest.deterministic:
    distribution: categorical
    values:
      - "true"
      - "false"
  input.backtest.tickers:
    distribution: categorical
    values:
      - [AAPL]
  input.dataset:
    distribution: constant
    value: DayFrequencyDataset
  input.decisionPriceFeature:
    distribution: constant
    value: TP
  input.embargoRatio:
    distribution: constant
    value: 0.03
  input.validationSplitRatio:
    distribution: constant
    value: 0.4
  input.start:
    distribution: constant
    value: 1/8/2016
  input.end:
    distribution: constant
    value: 1/8/2021
  input.features:
    distribution: categorical
    values:
      - [Close, Open, High, Low, Volume]
      - [Close, Open, High, Low]
      - [Close, Open]
  input.technicalIndicators:
    distribution: categorical
    values:
      - [macd, rsi_30, cci_30, dx_30]
      - [macd, rsi_30]
      - [cci_30, dx_30]
      - [macd]
      - [rsi_30]
      - [cci_30]
      - [dx_30]
      - []
  input.includeWeekends:
    distribution: constant
    value: "false"
  input.market:
    distribution: constant
    value: Yahoo
  input.numAssetsPerDataset:
    distribution: constant
    value: 1
  input.periodLength:
    distribution: constant
    value: 1M
  input.scaleOnInterval:
    distribution: constant
    value: 1d
  input.scaler:
    distribution: constant
    value: MinMaxScaler
  input.tickers:
    distribution: constant
    value: [NASDAQ100]
  input.fineTuneTickers:
    distribution: constant
    value: [AAPL]
  input.windowSize:
    distribution: int_uniform
    max: 90
    min: 1
  meta.device:
    distribution: constant
    value: gpu
  meta.experimentTracker:
    distribution: constant
    value: wandb
  meta.logFrequencySteps:
    distribution: constant
    value: 10000
  train.batchSize:
    distribution: q_normal
    mu: 1024
    sigma: 256
  train.clipRange:
    distribution: normal
    mu: 0.3
    sigma: 0.1
  train.vfClipRange:
    distribution: normal
    mu: 0.3
    sigma: 0.1
  train.collectingNSteps:
    distribution: int_uniform
    max: 10240
    min: 2048
  train.entropyCoefficient:
    distribution: uniform
    max: 0.02
    min: 0.005
  train.totalTimesteps:
    distribution: constant
    value: 1300000
  train.fineTuneTotalTimesteps:
    distribution: constant
    value: 200000
  train.gaeLambda:
    distribution: uniform
    max: 1.
    min: 0.9
  train.gamma:
    distribution: uniform
    max: 1.0
    min: 0.9
  train.learningRate:
    distribution: uniform
    max: 0.0005
    min: 0.00005
  train.maxGradNorm:
    distribution: uniform
    max: 1
    min: 0.25
  train.nEpochs:
    distribution: int_uniform
    max: 10
    min: 3
  train.useSde:
    distribution: constant
    value: "false"
  train.sdeSampleFreq:
    distribution: int_uniform
    max: 4096
    min: 1024
  train.trainerName:
    distribution: constant
    value: Trainer
  train.vfCoefficient:
    distribution: normal
    mu: 1.
    sigma: 0.5
