hardware:
  device: "cuda"
input:
  market: "polonex"
  start_datetime: "2015/07/01"
  end_datetime: "2017/07/01"
  data_frequency: "30M"
  window_size: 31
  validation_split: 0.08
  render_prices: False
training:
  agent: "EIIEAgent"
  steps: 80000
  validation_every_step: 1000
  save_every_step: 10000
  learning_rate: 0.00028
  weight_decay: 5e-08
  learning_rate_decay: 1.0
  learning_rate_decay_steps: 50000
  batch_size: 5
  buffer_biased: 0.00005
  optimizer: "Adam"
  loss_function: "loss_function6"
market:
  commission: 0.0025
